### ISSUE TITLE
RigidBody with Trimesh Collider panics on collision

### ISSUE THREAD

**Issue by ElnuDev** [dimforge/rapier#48] opened 2020-10-31 02:48 UTC
I'm having an issue with this rigidbody with a trimesh collider on it. As soon as it hits ground, the program panics with the following error:

`
thread 'main' panicked at 'Vector cross product dimension mismatch: must be (3, 1) or (1, 3) but found (2, 1).', /home/elnu/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.23.0/src/base/matrix.rs:1674:9
`

![trimesh-bug](https://user-images.githubusercontent.com/9874955/97769211-2f1a8700-1ae6-11eb-86fd-ace537ff60c9.gif)

The only thing I'm doing to the `RigidBody` after initialization is settings its `mass_properties.inv_mass`. Otherwise, it wouldn't fall at all, but get no errors (even on collisions). Any thoughts on why this is happening? Is it a bug?

**Comment by rezural** [comment] 2020-10-31 06:59
try 

```
RUST_BACKTRACE=full cargo run
```

**Comment by sebcrozet** [comment] 2020-10-31 13:31
Thank you for reporting this issue! 2D trimesh have not been fully tested yet.
I'm closing this as it is a duplicate of #7.

**Closed by sebcrozet** 2020-10-31 13:31 UTC

**Comment by ElnuDev** [comment] 2020-10-31 17:20
@rezural Here's the back trace:
```
thread 'main' panicked at 'Vector cross product dimension mismatch: must be (3, 1) or (1, 3) but found (2, 1).', /home/elnu/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.23.0/src/base/matrix.rs:1674:9
stack backtrace:
   0:     0x562d3a222560 - std::backtrace_rs::backtrace::libunwind::trace::h577ea05e9ca4629a
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x562d3a222560 - std::backtrace_rs::backtrace::trace_unsynchronized::h50b9b72b84c7dd56
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x562d3a222560 - std::sys_common::backtrace::_print_fmt::h6541cf9823837fac
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:79
   3:     0x562d3a222560 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf64fbff071026df5
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:58
   4:     0x562d3a245bcc - core::fmt::write::h9ddafa4860d8adff
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/fmt/mod.rs:1082
   5:     0x562d3a21f457 - std::io::Write::write_fmt::h1d2ee292d2b65481
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/mod.rs:1514
   6:     0x562d3a224c70 - std::sys_common::backtrace::_print::ha25f9ff5080d886d
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:61
   7:     0x562d3a224c70 - std::sys_common::backtrace::print::h213e8aa8dc5405c0
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:48
   8:     0x562d3a224c70 - std::panicking::default_hook::{{closure}}::h6482fae49ef9d963
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:200
   9:     0x562d3a2249bc - std::panicking::default_hook::he30ad7589e0970f9
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:219
  10:     0x562d3a2252d3 - std::panicking::rust_panic_with_hook::haa1ed36ada4ffb03
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:569
  11:     0x562d3a224ea9 - std::panicking::begin_panic_handler::{{closure}}::h7001af1bb21aeaeb
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:476
  12:     0x562d3a2229ec - std::sys_common::backtrace::__rust_end_short_backtrace::h39910f557f5f2367
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153
  13:     0x562d3a224e69 - rust_begin_unwind
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
  14:     0x562d3a224e1b - std::panicking::begin_panic_fmt::hc1b1320af38b7e12
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:429
  15:     0x562d39883001 - nalgebra::base::matrix::Matrix<N,R,C,S>::cross::hd07df064944509c3
                               at /home/elnu/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.23.0/src/base/matrix.rs:1674
  16:     0x562d398f3426 - ncollide2d::shape::triangle::Triangle<N>::scaled_normal::h7079ae0c2a4d902c
                               at /home/elnu/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide2d-0.26.0/src/shape/triangle.rs:170
  17:     0x562d398f34cf - ncollide2d::shape::triangle::Triangle<N>::normal::h367069eab55e285a
                               at /home/elnu/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide2d-0.26.0/src/shape/triangle.rs:138
  18:     0x562d398c0ae0 - rapier2d::geometry::sat::triangle_cuboid_find_local_separating_normal_oneway::hc5cdd75848ebf677
                               at /home/elnu/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.3.0/src/geometry/sat.rs:296
  19:     0x562d398e9abe - rapier2d::geometry::contact_generator::cuboid_triangle_contact_generator::generate_contacts::h58bfffc4833284d3
                               at /home/elnu/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.3.0/src/geometry/contact_generator/cuboid_triangle_contact_generator.rs:70
  20:     0x562d398e98dc - rapier2d::geometry::contact_generator::cuboid_triangle_contact_generator::generate_contacts_cuboid_triangle::h3fab0221adbf68f8
                               at /home/elnu/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.3.0/src/geometry/contact_generator/cuboid_triangle_contact_generator.rs:27
  21:     0x562d3992ea07 - rapier2d::geometry::contact_generator::trimesh_shape_contact_generator::do_generate_contacts::h949c013ffb2cd56e
                               at /home/elnu/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.3.0/src/geometry/contact_generator/trimesh_shape_contact_generator.rs:195
  22:     0x562d3992da73 - rapier2d::geometry::contact_generator::trimesh_shape_contact_generator::generate_contacts_trimesh_shape::h12f3ee561c45f6c6
                               at /home/elnu/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.3.0/src/geometry/contact_generator/trimesh_shape_contact_generator.rs:30
  23:     0x562d3995b87f - rapier2d::geometry::contact_generator::contact_generator::ContactPhase::generate_contacts::h26a3cc7a4d13c013
                               at /home/elnu/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.3.0/src/geometry/contact_generator/contact_generator.rs:27
  24:     0x562d3989c4ea - rapier2d::geometry::narrow_phase::NarrowPhase::compute_contacts::{{closure}}::h2eed11015ac52d16
                               at /home/elnu/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.3.0/src/geometry/narrow_phase.rs:438
  25:     0x562d3995b397 - <core::slice::IterMut<T> as core::iter::traits::iterator::Iterator>::for_each::h3b23c7225261a772
                               at /home/elnu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/mod.rs:3807
  26:     0x562d3989bdf1 - rapier2d::geometry::narrow_phase::NarrowPhase::compute_contacts::h0595d7a12aab69e3
                               at /home/elnu/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.3.0/src/geometry/narrow_phase.rs:371
  27:     0x562d3995d013 - rapier2d::pipeline::physics_pipeline::PhysicsPipeline::step::h53f1ab797c515e64
                               at /home/elnu/.cargo/registry/src/github.com-1ecc6299db9ec823/rapier2d-0.3.0/src/pipeline/physics_pipeline.rs:114
  28:     0x562d398504dd - pong::physics_world::PhysicsWorld::step::h22c55d014f689427
                               at /home/elnu/pong/src/physics_world.rs:40
  29:     0x562d398500a3 - pong::systems::physics::system_physics::he8b61c8bd0f9bda5
                               at /home/elnu/pong/src/systems/physics.rs:7
  30:     0x562d3984680d - <pong::MainState as ggez::event::EventHandler>::update::h22ad57697c96f4ae
                               at /home/elnu/pong/src/main.rs:46
  31:     0x562d39853343 - ggez::event::run::hd783a229cff1d1d4
                               at /home/elnu/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.5.1/src/event.rs:280
  32:     0x562d398479d5 - pong::main::hc2c35b08bf51898c
                               at /home/elnu/pong/src/main.rs:197
  33:     0x562d3984b172 - core::ops::function::FnOnce::call_once::h556b4bd16c029875
                               at /home/elnu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  34:     0x562d39836e6a - std::sys_common::backtrace::__rust_begin_short_backtrace::h0ab6b0ee8bbaf655
                               at /home/elnu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
  35:     0x562d39829916 - std::rt::lang_start::{{closure}}::hafe8d4dbba57cd7e
                               at /home/elnu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66
  36:     0x562d3a2256d1 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6a3209f124be2235
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:259
  37:     0x562d3a2256d1 - std::panicking::try::do_call::h88ce358792b64df0
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373
  38:     0x562d3a2256d1 - std::panicking::try::h6311c259678e50fc
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337
  39:     0x562d3a2256d1 - std::panic::catch_unwind::h56c5716807d659a1
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379
  40:     0x562d3a2256d1 - std::rt::lang_start_internal::h73711f37ecfcb277
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/rt.rs:51
  41:     0x562d398298e7 - std::rt::lang_start::h0d246d2afed7bd38
                               at /home/elnu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65
  42:     0x562d39847e3a - main
  43:     0x7f0f084660b3 - __libc_start_main
  44:     0x562d3982810e - _start
  45:                0x0 - <unknown>
```
