### ISSUE TITLE
set_motor_velocity

### ISSUE THREAD

**Issue by KnstAnt** [dimforge/rapier#344] opened 2022-06-09 20:40 UTC
I cannot change the parameters of a motor after it has been created. I used set_motor_velocity. The console output shows that the data in the motor has changed, but the behavior of the associated colliders does not change. Perhaps it is worth adding work with set_motor_velocity to the joint example?

**Comment by KnstAnt** [comment] 2022-09-08 22:05
I found a great project using motor velocity: https://github.com/RichTeaMan/combine-derby.git

**Comment by taslater** [comment] 2024-05-04 22:34
For anyone who stumbles on this one in the future, I can confirm that the method `set_motor_velocity()` changes the value of the `target_vel` property on `JointMotor`, but that has no impact on the physics pipeline. I'm not sure why this is the case (possibly because the pipeline does not use the reference to ImpulseJoint, using the GenericJoint instead?), but I can recommend the following simple approach to simulating a dynamically changing motor:
```rust
for (
    _joint_handle,
    impulse_joint
) in self.impulse_joint_set.iter_mut() {
    // impulse_joint.data.set_motor_velocity(
    //     JointAxis::X,
    //     TARGET_VELOCITY * self.motor_direction,
    //     DAMPING_FACTOR,
    // );
    self.rigid_body_set.get_mut(impulse_joint.body1).unwrap().apply_torque_impulse(
        self.motor_direction * MOTOR_MAX_TORQUE,
        true,
    );
    self.rigid_body_set.get_mut(impulse_joint.body2).unwrap().apply_torque_impulse(
        -self.motor_direction * MOTOR_MAX_TORQUE,
        true,
    );
}
```
As you can see, I commented out the "broken" approach using `set_motor_velocity()`. But directly applying impulse (torque in my case) works.

**Comment by sebcrozet** [comment] 2024-05-05 08:47
@taslater In your call to `set_motor_velocity`, you specified the axis `JointAxis::X`. This is the axis for the translational movement of the motor (which won’t have any effect if you are doing that on joints locking translations (like revolute or spherical joints). You should use the `JointAxis::AngX` axis instead. Please let me know if that worked.

Considering how old the original issue is, I suppose KnstAnt was using an older version of rapier that had issue with motor implementations (on previous iterations of rapier’s solver).

**Comment by taslater** [comment] 2024-05-05 13:05
Wonderful! You are absolutely right. Thank you. I consider this issue resolved.

**Comment by sebcrozet** [comment] 2024-05-05 13:08
@taslater Perfect, glad to hear that worked.
@KnstAnt I’m closing this issue since it’s pretty old and it should work properly now. Don’t hesitate to open a new one if you are still having issues.

**Closed by sebcrozet** 2024-05-05 13:08 UTC
