### ISSUE TITLE
Rigidbody and non-rigidbody colliding often ends with tunneling (2D)

### ISSUE THREAD

**Issue by elyshaffir** [dimforge/rapier#421] opened 2022-11-26 18:41 UTC
Hello everyone, I have been experimenting with a simulation that involves a rigidbody colliding with many colliders (not attached to rigid bodies).
I noticed that even with `ccd_enabled` for the rigidbody it often still either passes through colliders or gets stuck in them.

Am I missing something? is this a known bug?

Some more details that might help shed some light:
* The sizes of the colliders are somewhat different - the rigidbody is 64x64 cuboid and the other colliders are either 1x1 or a polyline.
* The velocity of the rigidbody is typically `apply_impulse` of `900000` in some direction, sometimes multiple impulses in a row.

**Comment by elyshaffir** [comment] 2023-01-31 20:26
Hi, sorry for the late response - what do you mean debug rendering?

**Comment by sebcrozet** [comment] 2023-03-26 14:14
This can be a bug, or some limitation of the CCD implementation. Hard to tell without knowing the exact configuration. For example, if you keep applying very large impulses toward a wall, while the rigid-body is already penetrating this wall, you may trigger some tunneling since rigid-body have to still move at least a little at each frame to prevent it from getting stuck due to rounding errors.

**Comment by sebcrozet** [comment] 2023-07-08 12:37
Closing this as it is lacking details to reproduce the problem.

**Closed by sebcrozet** 2023-07-08 12:37 UTC
