### ISSUE TITLE
point of collision with HeightField

### ISSUE THREAD

**Issue by politrons** [dimforge/rapier#542] opened 2023-10-27 13:07 UTC
In `rapier2d` having a collider with `GenericHeightField`. Inside we can have all heights, but there is any chance to know when I'm using collision detection, to which particular `height` my `body` collide?

Regards.

**Comment by sebcrozet** [comment] 2024-01-28 22:17
Sorry for the late answer. If you are detecting collisions with the heightfield, I assume you will get contact points. The contact point position will give you the height of that collision.
Closing now as the issue is a bit old, but feel free to reopen if this is still an open question.

**Closed by sebcrozet** 2024-01-28 22:17 UTC
