### ISSUE TITLE
Trimesh internal edges cause incorrect simulation

### ISSUE THREAD

**Issue by HexaField** [dimforge/rapier#404] opened 2022-10-17 04:25 UTC
Ball colliders seem to be affected by trimesh internal edges, rolling at odd angles and along edges.

**Comment by ottoville** [comment] 2022-10-21 21:22
This must be duplicate of https://github.com/dimforge/rapier/issues/372
I think this is a major issue, making trimesh very hard to use in projects.

**Comment by HexaField** [comment] 2022-10-22 05:34
> This must be duplicate of #372 I think this is a major issue, making trimesh unusable.

This is not the same issue. Your issue is due to rolling friction not being implemented yet, this issue is to do with a bug in triangle mesh triangulation.

**Comment by ottoville** [comment] 2022-10-22 09:18
> > This must be duplicate of #372 I think this is a major issue, making trimesh unusable.
> 
> This is not the same issue. Your issue is due to rolling friction not being implemented yet, this issue is to do with a bug in triangle mesh triangulation.

I see, so these two issues together results chaotic behavior of rolling shapes with triangle mesh.

**Comment by sebcrozet** [comment] 2022-10-30 10:39
This will be addressed (for the 3D version of Rapier) by https://github.com/dimforge/parry/pull/101.

**Comment by sebcrozet** [comment] 2023-01-01 16:26
This was addressed and released in Rapier 0.16

**Closed by sebcrozet** 2023-01-01 16:26 UTC
